server {
    listen 80;
    server_name domain1.com domain2.com domain3.com domain4.com domain5.com domain6.com domain7.com domain8.com domain9.com domain10.com smetemplate.xyz;

    # Serve static files for your frontend app
    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
    }

    # Proxy API requests to the backend API container
    location /api/ {
        proxy_pass http://sme_api:3011;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}
