services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    container_name: sme_api
    ports:
      - "3011:3011"
    volumes:
      - ./tenant_configs.json:/app/tenant_configs.json:ro
    environment:
      - NODE_ENV=production

  client:
    build: ./client
    container_name: sme_client
    ports:
      - "8080:80"
    depends_on:
      - api
    environment:
      - NODE_ENV=production
